version: 1
update_configs:
  # Update Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
  # Keep src up to date, batching pull requests weekly
  - package_manager: "go:dep"
    directory: "/src/acceptance_tests"
    update_schedule: "weekly"