---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker
inputs:
  - name: identity-ci
  - name: uaa-release
run:
  path: uaa-release/ci/tasks/test-acceptance.sh
